#API Strings Constant

DATA_SUCCESS        = 'Data successfully returned!'
LIMIT_NOT_SPECIFIED = 'Limit must be specified!'
LIMIT_EXCEEDED      = 'Limit exceeded, limit must be less than the total data!'
NO_DATA_FOUND       = 'No data can be returned!'
OFFSET_EXCEEDED     = 'Offset exceeded, offset must be less than the total data!'
KEYWORD_REQUIRED    = 'Please input a keyword!'
AREA_TYPE_NOT_FOUND = 'Area type not found!'
MAX_LIMIT           = 'Max limit for data is 100!'
ROOT_MESSAGE        = 'Welcome to StrayNeko API!. Hope this API can help~.'
PROJECT_REPOSITORY  = 'https://github.com/Strayneko/API-Lokasi-Indonesia'
CREATOR_NAME        = 'StrayNeko'
CREATOR_MAIL        = 'bayurendi10@gmail.com'
CREATOR_SITE        = 'strayneko.github.io'
CREATOR_GITHUB      = 'https://github.com/strayneko'
